packages <- c(
    'tidyverse'
    , 'coefplot'
    , 'DBI'
    , 'dbplyr'
    , 'DT'
    , 'ggthemes'
    , 'glmnet'
    , 'here'
    , 'jsonlite'
    , 'knitr'
    , 'leaflet'
    , 'odbc'
    , 'plotly'
    , 'recipes'
    , 'rmarkdown'
    , 'rprojroot'
    , 'RSQLite'
    , 'rvest'
    , 'threejs'
    , 'useful'
    , 'UsingR'
    , 'xgboost'
    , 'xml2'
    , 'rpart.plot'
)
install.packages(packages)